### ISSUE TITLE
relation "docs" does not exist

### ISSUE THREAD

**Issue by terrisgit** [robconery/pg_docs_api#2]
Do I need to run anything besides api.sql? I'm getting an error with your example.

select \* from save_document('monkies', '{"name" : "foofer"}');

SQL Error: ERROR:  Error: Error: relation "docs" does not exist
DETAIL:  save_document() LINE 6:     plv8.execute("select create_document_table('" + tbl + "');");

**Comment by robconery** [comment]
I sit here with a beer in hand, thinking about the Seahawks game where they lost in the last minute of the game for like the 5th time this season... and I'm in a Slack chat with 5 friends, two of which I'm trying to build a new application. My daughter is waiting for me to read her a bedtime story and I'm finishing off a KILLER 80s playlist on Spotify...

`api.sql`? I need _just a bit more detail_ here to catch up with what you're doing. I want to help - I do. Just  a bit more detail would help me read to my daughter just a few minutes faster...

**Comment by terrisgit** [comment]
Hi, sorry about the Seahawks. I imagine they will beat the 49ers on Sunday. This question is regarding your pg_docs_api project on github. I watched your talk and decided to do things your way although I am  old and know my way around RDBMS just fine. Like you said, I want to get to mars first. Anyway, I ran api.sql on my server but I am not able to invoke save_document due to error "relation "docs" does not exist." I will dig into it. By the way, I have not used Slack but have started on Discord which works with larger teams. http://discordapp.com I too enjoy beer and the days of reading to my daughter are behind me. I guess I'm back to only having work again.

**Comment by robconery** [comment]
Ahh - thanks for this! Yes, you should be able to run api.sql to seed the functions, and then save should create the functions for you. That's the idea at least. I'll give it a go tonite when I get a chance.

**Comment by terrisgit** [comment]
The fix is in create_document_table .. add variable name to string instead of hard-coded 'doc'

  plv8.execute("create index idx_" + name + " on " + name + " using GIN(body jsonb_path_ops)");
  plv8.execute("create index idx_" + name + "_search on " + name + " using GIN(search)");

**Comment by terrisgit** [comment]
By the way, if you intend to keep this project going, could I please ask for the id to be text instead of int

**Comment by terrisgit** [comment]
That fix is already checked in. It appears that I got an old api.sql somehow. My apologies.
