### ISSUE TITLE
Question about speed.

### ISSUE THREAD

**Issue by vegarringdal** [robconery/pg_docs_api#6]
Hi

Saw you on youtube her: (great video)
https://www.youtube.com/watch?v=rg_GiOZ5Owk

Postgresql looks like a lot of FUN, for the smaller applications I want to make, sqlite will prb be enough.

PLv8 is that faster or slower then PLPGSQL?
I,m pretty sure Im going to prefer the PLV8, but nice to know if its is a lot slower, or faster than the options shipped with postgresql.

**Comment by robconery** [comment]
Hey sorry, I didn't get a notification about this! PLV8 executes the same, I think, as it would for Node etc. I haven't seen anything about speed vs. PLPGSQL.
