### ISSUE TITLE
Bulk insert with postgreSQL

### ISSUE THREAD

**Issue by venkatbachan09** [robconery/pg_docs_api#7]
Hi Rob,

i saw your presentation, it was fantastic..:)

but my issue is that how can we insert bulk of documents into details jsonb and if we insert then how the primary key generate automatically, please help me.

Thanks.

**Comment by robconery** [comment]
Hey thanks :). I should close this repo as I have another one called dox that I like much better...

You would need to add the array as jsonb then loop over the items in a function, inserting as you go.

**Comment by venkatbachan09** [comment]
hmm thanks for the quick reply, 
i can able to that, but performance will be matter right, i read many places that we can use COPY,
do have any idea that how can we use COPY.

**Comment by venkatbachan09** [comment]
Thanks, closed
